### ISSUE TITLE
DA presentation

### ISSUE THREAD

**Issue by jgomezdans** [UCL-EO/Workshop2022#11]
- [x] Contact HangHui re MCMC
- [ ] Need to get some form of within-season forecast example from Hongyuan/Nicola
## Talk contents
- [x] DA concepts (just an outline, mostly pictures)
	- [x] Drivers/States/Parameters and models
    - [x] Model & observation uncertainties (examples)
- [x] Assimilation: blending models & observations. Mostly pictures and no maths
    - [x] Correct the model trajectory/state: filters
    - [x] Pros/cons 
    - [x] Variational methods:  Parameter estimation
    - [x] Pros/cons
    - [x] Ensemble methods
- [ ] Example of system working with the crop model
    - [x] Ensemble generation (parameters, possibly weather)
    - [x] Linking model predictions with observed LAI
    - [x] Yield prediction
    - [x] Model parameter interpretation
- [ ] DA and within-season forecasting introduction @Ma-hy to provide some slides

**Comment by Ma-hy** [comment]
as for within-season forecasting introduction, what kind of content should I include? I have generated some yield prediction boxplot, what else?
![image](https://user-images.githubusercontent.com/17977287/156215686-e875b322-e85f-451a-8522-702f419e1fff.png)

**Comment by profLewis** [comment]
Nicola will be doing more in within-season, so pls liase with her on that.

Thanks

Lewis

Professor Lewis, NCEO/UCL
________________________________

**Comment by jgomezdans** [comment]
[First draft of talk](https://docs.google.com/presentation/d/1D8o2c1XbBGy-455h7CiLuMQjWnUDZKK1N10Qq9OO_9g/edit?usp=sharing)
Still missing:
* Agree with @NPounder  whether I include something on within-season forecast
* Conclusions ;-)

**Comment by profLewis** [comment]
Hi thanks

I think maybe you have 2 15 min talks in there …

Maybe one on generic concepts (like the 1st half) and one on application to Ghana. That would give more time to the details of how we tackled the particular problem in Ghana and some detail in the results of that.that, in turn would serve as the basis for a paper on this. It would also serve to help anyone who wants to follow up and repeat it know what to do.

The in-season parts would probably be best as as separate talk from Nicola, if that’s possible. If not, then sure, wrap in here. We can discuss today.

Lewis

Professor Lewis, NCEO/UCL
________________________________

**Comment by jgomezdans** [comment]
Field data [detailed talk](https://docs.google.com/presentation/d/1S3TkJICEMmKcBnz8WcAWNWjOXrDoAWFizELSg1VRELg/edit?usp=sharing)

**Comment by jgomezdans** [comment]
I'm done with both talks, so closing this.
