### ISSUE TITLE
Sort out field pictures by field in Google Photos

### ISSUE THREAD

**Issue by jgomezdans** [UCL-EO/Workshop2022#16]
WE need a URL for each field folder photos

@MarcYin

**Comment by profLewis** [comment]
Tuesday

**Comment by MarcYin** [comment]
Have not received the field photos yet @asarefi

**Comment by MarcYin** [comment]
Have not received the field photos yet @asarefi

**Comment by MarcYin** [comment]
Field photos has been added to the map
![Screenshot 2022-03-02 at 18 33 36](https://user-images.githubusercontent.com/19539641/156426354-e1c1387e-05c4-45e4-aa88-bbbab3f407e0.png)

I will close this issue for now.
