### ISSUE TITLE
Send invitations to potential participants 

### ISSUE THREAD

**Issue by qwu-570** [UCL-EO/Workshop2022#21]
Qingling and Kofi has updated the draft invitation. Any final proof @profLewis ?
https://liveuclac-my.sharepoint.com/:w:/r/personal/ucfaqqw_ucl_ac_uk/_layouts/15/Doc.aspx?sourcedoc=%7B6D15C7A1-C4FF-4E2B-A8A1-C1D6120642DC%7D&file=Stakeholder-invitation-letter-draft.docx&action=default&mobileredirect=true

**Comment by profLewis** [comment]
Ive edited this now. @qwu-570 - can you let Kofi know?

Lewis
